---
{{- if .Values.operator.crd.create }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitoringdashboards.monitoring.kiali.io
  labels:
    {{ include "kiali-operator.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.operator.crd.cleanupBeforeInstall }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
    "helm.sh/hook": "crd-install"
spec:
  group: monitoring.kiali.io
  names:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kialis.kiali.io
  labels:
    {{ include "kiali-operator.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.operator.crd.cleanupBeforeInstall }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
    "helm.sh/hook": "crd-install"
spec:
  group: kiali.io
  names:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
{{- end }}
