---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  labels:
    {{- include "kiali-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali-operator
  template:
    metadata:
      name: {{ include "kiali-operator.fullname" . }}
      labels:
        {{ include "kiali-operator.labels" . | nindent 8 }}
    spec:
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kiali-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}@{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - "--zap-level=info"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
            {{- if .Values.operator.clusterWide }}
              value: ""
            {{- else }}
              value: {{ .Chart.Namespace }}
            {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "kiali-operator"
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
            - name: ANSIBLE_VERBOSITY_KIALI_KIALI_IO
              value: "1"
          ports:
            - name: http-metrics
              containerPort: 8383
            - name: cr-metrics
              containerPort: 8686
          #livenessProbe: {}
          #readinessProbe: {}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      volumes:
        - name: runner
          emptyDir: {}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
