{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kiali-operator.serviceAccountName" . }}
  labels:
    {{ include "kiali-operator.labels" . | nindent 4 }}
{{- end -}}
